// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';


function isLeapYear(n) {
  if (n % 400 === 0) {
    return true;
  } else if (n % 100 === 0) {
    return false;
  } else {
    return n % 4 === 0;
  }
}

exports.isLeapYear = isLeapYear;
/* No side effect */
