// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';


var BinarySearch_test = 0;

var BinarySearch = 0;

exports.BinarySearch_test = BinarySearch_test;
exports.BinarySearch = BinarySearch;
/* No side effect */
