// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';


function planetPeriodInEarthYear(p) {
  switch (p) {
    case 0 : 
        return 0.2408467;
    case 1 : 
        return 0.61519726;
    case 2 : 
        return 1.0;
    case 3 : 
        return 1.8808158;
    case 4 : 
        return 11.862615;
    case 5 : 
        return 29.447498;
    case 6 : 
        return 164.79132;
    case 7 : 
        return 84.016846;
    
  }
}

function ageOn(p, s) {
  return s / 31557600.0 / planetPeriodInEarthYear(p);
}

exports.ageOn = ageOn;
/* No side effect */
