// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';


var Minesweeper_test = 0;

var Minesweeper = 0;

exports.Minesweeper_test = Minesweeper_test;
exports.Minesweeper = Minesweeper;
/* No side effect */
