// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Anagram$Anagram = require("../src/Anagram.bs.js");

describe("Anagram", (function () {
        Jest.test("no matches", (function () {
                return Jest.Expect[/* toEqual */12](/* [] */0, Jest.Expect[/* expect */0](Anagram$Anagram.anagrams("diaper", /* :: */[
                                    "hello",
                                    /* :: */[
                                      "world",
                                      /* :: */[
                                        "zombies",
                                        /* :: */[
                                          "pants",
                                          /* [] */0
                                        ]
                                      ]
                                    ]
                                  ])));
              }));
        Jest.test("detects two anagrams", (function () {
                return Jest.Expect[/* toEqual */12](/* :: */[
                            "stream",
                            /* :: */[
                              "maters",
                              /* [] */0
                            ]
                          ], Jest.Expect[/* expect */0](Anagram$Anagram.anagrams("master", /* :: */[
                                    "stream",
                                    /* :: */[
                                      "pigeon",
                                      /* :: */[
                                        "maters",
                                        /* [] */0
                                      ]
                                    ]
                                  ])));
              }));
        Jest.test("does not detect anagram subsets", (function () {
                return Jest.Expect[/* toEqual */12](/* [] */0, Jest.Expect[/* expect */0](Anagram$Anagram.anagrams("good", /* :: */[
                                    "dog",
                                    /* :: */[
                                      "goody",
                                      /* [] */0
                                    ]
                                  ])));
              }));
        Jest.test("detects anagram", (function () {
                return Jest.Expect[/* toEqual */12](/* :: */[
                            "inlets",
                            /* [] */0
                          ], Jest.Expect[/* expect */0](Anagram$Anagram.anagrams("listen", /* :: */[
                                    "enlists",
                                    /* :: */[
                                      "google",
                                      /* :: */[
                                        "inlets",
                                        /* :: */[
                                          "banana",
                                          /* [] */0
                                        ]
                                      ]
                                    ]
                                  ])));
              }));
        Jest.test("detects three anagrams", (function () {
                return Jest.Expect[/* toEqual */12](/* :: */[
                            "gallery",
                            /* :: */[
                              "regally",
                              /* :: */[
                                "largely",
                                /* [] */0
                              ]
                            ]
                          ], Jest.Expect[/* expect */0](Anagram$Anagram.anagrams("allergy", /* :: */[
                                    "gallery",
                                    /* :: */[
                                      "ballerina",
                                      /* :: */[
                                        "regally",
                                        /* :: */[
                                          "clergy",
                                          /* :: */[
                                            "largely",
                                            /* :: */[
                                              "leading",
                                              /* [] */0
                                            ]
                                          ]
                                        ]
                                      ]
                                    ]
                                  ])));
              }));
        Jest.test("does not detect non-anagrams(with identical checksum", (function () {
                return Jest.Expect[/* toEqual */12](/* [] */0, Jest.Expect[/* expect */0](Anagram$Anagram.anagrams("mass", /* :: */[
                                    "last",
                                    /* [] */0
                                  ])));
              }));
        Jest.test("detects anagrams(case-insensitively", (function () {
                return Jest.Expect[/* toEqual */12](/* :: */[
                            "Carthorse",
                            /* [] */0
                          ], Jest.Expect[/* expect */0](Anagram$Anagram.anagrams("Orchestra", /* :: */[
                                    "cashregister",
                                    /* :: */[
                                      "Carthorse",
                                      /* :: */[
                                        "radishes",
                                        /* [] */0
                                      ]
                                    ]
                                  ])));
              }));
        Jest.test("detects anagrams(using case-insensitive subject", (function () {
                return Jest.Expect[/* toEqual */12](/* :: */[
                            "carthorse",
                            /* [] */0
                          ], Jest.Expect[/* expect */0](Anagram$Anagram.anagrams("Orchestra", /* :: */[
                                    "cashregister",
                                    /* :: */[
                                      "carthorse",
                                      /* :: */[
                                        "radishes",
                                        /* [] */0
                                      ]
                                    ]
                                  ])));
              }));
        Jest.test("detects anagrams(using case-insensitive possible matches", (function () {
                return Jest.Expect[/* toEqual */12](/* :: */[
                            "Carthorse",
                            /* [] */0
                          ], Jest.Expect[/* expect */0](Anagram$Anagram.anagrams("orchestra", /* :: */[
                                    "cashregister",
                                    /* :: */[
                                      "Carthorse",
                                      /* :: */[
                                        "radishes",
                                        /* [] */0
                                      ]
                                    ]
                                  ])));
              }));
        Jest.test("does not detect a anagram if the original word is repeated", (function () {
                return Jest.Expect[/* toEqual */12](/* [] */0, Jest.Expect[/* expect */0](Anagram$Anagram.anagrams("go", /* :: */[
                                    "go Go GO",
                                    /* [] */0
                                  ])));
              }));
        Jest.test("anagrams(must use all letters exactly once", (function () {
                return Jest.Expect[/* toEqual */12](/* [] */0, Jest.Expect[/* expect */0](Anagram$Anagram.anagrams("tapper", /* :: */[
                                    "patter",
                                    /* [] */0
                                  ])));
              }));
        return Jest.test("capital word is not own anagram", (function () {
                      return Jest.Expect[/* toEqual */12](/* [] */0, Jest.Expect[/* expect */0](Anagram$Anagram.anagrams("BANANA", /* :: */[
                                          "Banana",
                                          /* [] */0
                                        ])));
                    }));
      }));

/*  Not a pure module */
