// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var $$String = require("bs-platform/lib/js/string.js");

function isPangram(xs) {
  return $$Array.of_list(List.sort_uniq($$String.compare, $$Array.to_list(xs.toLowerCase().replace((/[^[[a-z]|[A-Z]|[0-9]]]/g), "").split("")))).join("") === "abcdefghijklmnopqrstuvwxyz";
}

exports.isPangram = isPangram;
/* No side effect */
