// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");

function dnaToRna(d) {
  switch (d) {
    case 0 : 
        return /* U */3;
    case 1 : 
        return /* G */2;
    case 2 : 
        return /* C */1;
    case 3 : 
        return /* A */0;
    
  }
}

function toRna(param) {
  return List.map(dnaToRna, param);
}

exports.toRna = toRna;
/* No side effect */
