// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';


var Accumulate_test = 0;

var Accumulate = 0;

exports.Accumulate_test = Accumulate_test;
exports.Accumulate = Accumulate;
/* No side effect */
