// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';


var Change_test = 0;

var Change = 0;

exports.Change_test = Change_test;
exports.Change = Change;
/* No side effect */
