// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';


var Anagram_test = 0;

var Anagram = 0;

exports.Anagram_test = Anagram_test;
exports.Anagram = Anagram;
/* No side effect */
