// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function isPling(n) {
  var match = n % 3 === 0;
  if (match) {
    return "Pling";
  } else {
    return "";
  }
}

function isPlang(n) {
  var match = n % 5 === 0;
  if (match) {
    return "Plang";
  } else {
    return "";
  }
}

function isPlong(n) {
  var match = n % 7 === 0;
  if (match) {
    return "Plong";
  } else {
    return "";
  }
}

function raindrops(n) {
  var n$1 = n;
  var r = /* array */[
        isPling,
        isPlang,
        isPlong
      ].map((function (f) {
            return Curry._1(f, n);
          })).join("");
  var match = r.length;
  if (match !== 0) {
    return r;
  } else {
    return String(n$1);
  }
}

exports.raindrops = raindrops;
/* No side effect */
