// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';


var Pangram_test = 0;

var Pangram = 0;

exports.Pangram_test = Pangram_test;
exports.Pangram = Pangram;
/* No side effect */
