// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var $$String = require("bs-platform/lib/js/string.js");

function abbreviate(s) {
  return $$Array.map((function (w) {
                  return $$String.sub(w, 0, 1).toUpperCase();
                }), s.split((/[\s|-]+/g))).join("");
}

exports.abbreviate = abbreviate;
/* No side effect */
