// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';


var ArmstrongNumbers_test = 0;

var ArmstrongNumbers = 0;

exports.ArmstrongNumbers_test = ArmstrongNumbers_test;
exports.ArmstrongNumbers = ArmstrongNumbers;
/* No side effect */
