// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';


var RunLengthEncoding_test = 0;

var RunLengthEncoding = 0;

exports.RunLengthEncoding_test = RunLengthEncoding_test;
exports.RunLengthEncoding = RunLengthEncoding;
/* No side effect */
