// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';


var ProteinTranslation_test = 0;

var ProteinTranslation = 0;

exports.ProteinTranslation_test = ProteinTranslation_test;
exports.ProteinTranslation = ProteinTranslation;
/* No side effect */
