// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Allergies$Allergies = require("../src/Allergies.bs.js");

describe("Allergies", (function () {
        describe("isAllergicTo", (function () {
                describe("no Allergies means not allergic", (function () {
                        Jest.test("peanuts", (function () {
                                return Jest.Expect[/* toBe */2](false, Jest.Expect[/* expect */0](Allergies$Allergies.isAllergicTo("peanuts", 0)));
                              }));
                        Jest.test("cats", (function () {
                                return Jest.Expect[/* toBe */2](false, Jest.Expect[/* expect */0](Allergies$Allergies.isAllergicTo("cats", 0)));
                              }));
                        return Jest.test("strawberries", (function () {
                                      return Jest.Expect[/* toBe */2](false, Jest.Expect[/* expect */0](Allergies$Allergies.isAllergicTo("strawberries", 0)));
                                    }));
                      }));
                Jest.test("is allergic to eggs", (function () {
                        return Jest.Expect[/* toBe */2](true, Jest.Expect[/* expect */0](Allergies$Allergies.isAllergicTo("eggs", 1)));
                      }));
                describe("has the right allergies", (function () {
                        Jest.test("eggs", (function () {
                                return Jest.Expect[/* toBe */2](true, Jest.Expect[/* expect */0](Allergies$Allergies.isAllergicTo("eggs", 5)));
                              }));
                        Jest.test("shellfish", (function () {
                                return Jest.Expect[/* toBe */2](true, Jest.Expect[/* expect */0](Allergies$Allergies.isAllergicTo("shellfish", 5)));
                              }));
                        return Jest.test("strawberries", (function () {
                                      return Jest.Expect[/* toBe */2](false, Jest.Expect[/* expect */0](Allergies$Allergies.isAllergicTo("strawberries", 5)));
                                    }));
                      }));
                describe("toList", (function () {
                        Jest.test("no allergies at all", (function () {
                                return Jest.Expect[/* toEqual */12](/* [] */0, Jest.Expect[/* expect */0](Allergies$Allergies.toList(0)));
                              }));
                        Jest.test("allergic to just peanuts", (function () {
                                return Jest.Expect[/* toEqual */12](/* :: */[
                                            "peanuts",
                                            /* [] */0
                                          ], Jest.Expect[/* expect */0](Allergies$Allergies.toList(2)));
                              }));
                        Jest.test("allergic to everything", (function () {
                                return Jest.Expect[/* toEqual */12](/* :: */[
                                            "eggs",
                                            /* :: */[
                                              "peanuts",
                                              /* :: */[
                                                "shellfish",
                                                /* :: */[
                                                  "strawberries",
                                                  /* :: */[
                                                    "tomatoes",
                                                    /* :: */[
                                                      "chocolate",
                                                      /* :: */[
                                                        "pollen",
                                                        /* :: */[
                                                          "cats",
                                                          /* [] */0
                                                        ]
                                                      ]
                                                    ]
                                                  ]
                                                ]
                                              ]
                                            ]
                                          ], Jest.Expect[/* expect */0](Allergies$Allergies.toList(255)));
                              }));
                        Jest.test("ignore non allergen score parts", (function () {
                                return Jest.Expect[/* toEqual */12](/* :: */[
                                            "eggs",
                                            /* [] */0
                                          ], Jest.Expect[/* expect */0](Allergies$Allergies.toList(257)));
                              }));
                        return Jest.test("ignore all non allergen score parts", (function () {
                                      return Jest.Expect[/* toEqual */12](/* :: */[
                                                  "eggs",
                                                  /* :: */[
                                                    "shellfish",
                                                    /* :: */[
                                                      "strawberries",
                                                      /* :: */[
                                                        "tomatoes",
                                                        /* :: */[
                                                          "chocolate",
                                                          /* :: */[
                                                            "pollen",
                                                            /* :: */[
                                                              "cats",
                                                              /* [] */0
                                                            ]
                                                          ]
                                                        ]
                                                      ]
                                                    ]
                                                  ]
                                                ], Jest.Expect[/* expect */0](Allergies$Allergies.toList(509)));
                                    }));
                      }));
                return /* () */0;
              }));
        return /* () */0;
      }));

/*  Not a pure module */
