// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var ProteinTranslation$ProteinTranslation = require("../src/ProteinTranslation.bs.js");

describe("Protein Translation", (function () {
        Jest.test("Methionine RNA sequence", (function () {
                return Jest.Expect[/* toEqual */12](/* :: */[
                            "Methionine",
                            /* [] */0
                          ], Jest.Expect[/* expect */0](ProteinTranslation$ProteinTranslation.proteins("AUG")));
              }));
        Jest.test("Phenylalanine RNA sequence 1", (function () {
                return Jest.Expect[/* toEqual */12](/* :: */[
                            "Phenylalanine",
                            /* [] */0
                          ], Jest.Expect[/* expect */0](ProteinTranslation$ProteinTranslation.proteins("UUU")));
              }));
        Jest.test("Phenylalanine RNA sequence 2", (function () {
                return Jest.Expect[/* toEqual */12](/* :: */[
                            "Phenylalanine",
                            /* [] */0
                          ], Jest.Expect[/* expect */0](ProteinTranslation$ProteinTranslation.proteins("UUC")));
              }));
        Jest.test("Leucine RNA sequence 1", (function () {
                return Jest.Expect[/* toEqual */12](/* :: */[
                            "Leucine",
                            /* [] */0
                          ], Jest.Expect[/* expect */0](ProteinTranslation$ProteinTranslation.proteins("UUA")));
              }));
        Jest.test("Leucine RNA sequence 2", (function () {
                return Jest.Expect[/* toEqual */12](/* :: */[
                            "Leucine",
                            /* [] */0
                          ], Jest.Expect[/* expect */0](ProteinTranslation$ProteinTranslation.proteins("UUG")));
              }));
        Jest.test("Serine RNA sequence 1", (function () {
                return Jest.Expect[/* toEqual */12](/* :: */[
                            "Serine",
                            /* [] */0
                          ], Jest.Expect[/* expect */0](ProteinTranslation$ProteinTranslation.proteins("UCU")));
              }));
        Jest.test("Serine RNA sequence 2", (function () {
                return Jest.Expect[/* toEqual */12](/* :: */[
                            "Serine",
                            /* [] */0
                          ], Jest.Expect[/* expect */0](ProteinTranslation$ProteinTranslation.proteins("UCC")));
              }));
        Jest.test("Serine RNA sequence 3", (function () {
                return Jest.Expect[/* toEqual */12](/* :: */[
                            "Serine",
                            /* [] */0
                          ], Jest.Expect[/* expect */0](ProteinTranslation$ProteinTranslation.proteins("UCA")));
              }));
        Jest.test("Serine RNA sequence 4", (function () {
                return Jest.Expect[/* toEqual */12](/* :: */[
                            "Serine",
                            /* [] */0
                          ], Jest.Expect[/* expect */0](ProteinTranslation$ProteinTranslation.proteins("UCG")));
              }));
        Jest.test("Tyrosine RNA sequence 1", (function () {
                return Jest.Expect[/* toEqual */12](/* :: */[
                            "Tyrosine",
                            /* [] */0
                          ], Jest.Expect[/* expect */0](ProteinTranslation$ProteinTranslation.proteins("UAU")));
              }));
        Jest.test("Tyrosine RNA sequence 2", (function () {
                return Jest.Expect[/* toEqual */12](/* :: */[
                            "Tyrosine",
                            /* [] */0
                          ], Jest.Expect[/* expect */0](ProteinTranslation$ProteinTranslation.proteins("UAC")));
              }));
        Jest.test("Cysteine RNA sequence 1", (function () {
                return Jest.Expect[/* toEqual */12](/* :: */[
                            "Cysteine",
                            /* [] */0
                          ], Jest.Expect[/* expect */0](ProteinTranslation$ProteinTranslation.proteins("UGU")));
              }));
        Jest.test("Cysteine RNA sequence 2", (function () {
                return Jest.Expect[/* toEqual */12](/* :: */[
                            "Cysteine",
                            /* [] */0
                          ], Jest.Expect[/* expect */0](ProteinTranslation$ProteinTranslation.proteins("UGC")));
              }));
        Jest.test("Tryptophan RNA sequence", (function () {
                return Jest.Expect[/* toEqual */12](/* :: */[
                            "Tryptophan",
                            /* [] */0
                          ], Jest.Expect[/* expect */0](ProteinTranslation$ProteinTranslation.proteins("UGG")));
              }));
        Jest.test("STOP codon RNA sequence 1", (function () {
                return Jest.Expect[/* toEqual */12](/* [] */0, Jest.Expect[/* expect */0](ProteinTranslation$ProteinTranslation.proteins("UAA")));
              }));
        Jest.test("STOP codon RNA sequence 2", (function () {
                return Jest.Expect[/* toEqual */12](/* [] */0, Jest.Expect[/* expect */0](ProteinTranslation$ProteinTranslation.proteins("UAG")));
              }));
        Jest.test("STOP codon RNA sequence 3", (function () {
                return Jest.Expect[/* toEqual */12](/* [] */0, Jest.Expect[/* expect */0](ProteinTranslation$ProteinTranslation.proteins("UGA")));
              }));
        Jest.test("Translate RNA strand into correct protein list", (function () {
                return Jest.Expect[/* toEqual */12](/* :: */[
                            "Methionine",
                            /* :: */[
                              "Phenylalanine",
                              /* :: */[
                                "Tryptophan",
                                /* [] */0
                              ]
                            ]
                          ], Jest.Expect[/* expect */0](ProteinTranslation$ProteinTranslation.proteins("AUGUUUUGG")));
              }));
        Jest.test("Translation stops if STOP codon at beginning of sequence", (function () {
                return Jest.Expect[/* toEqual */12](/* [] */0, Jest.Expect[/* expect */0](ProteinTranslation$ProteinTranslation.proteins("UAGUGG")));
              }));
        Jest.test("Translation stops if STOP codon at end of two-codon sequence", (function () {
                return Jest.Expect[/* toEqual */12](/* :: */[
                            "Tryptophan",
                            /* [] */0
                          ], Jest.Expect[/* expect */0](ProteinTranslation$ProteinTranslation.proteins("UGGUAG")));
              }));
        Jest.test("Translation stops if STOP codon at end of three-codon sequence", (function () {
                return Jest.Expect[/* toEqual */12](/* :: */[
                            "Methionine",
                            /* :: */[
                              "Phenylalanine",
                              /* [] */0
                            ]
                          ], Jest.Expect[/* expect */0](ProteinTranslation$ProteinTranslation.proteins("AUGUUUUAA")));
              }));
        Jest.test("Translation stops if STOP codon in middle of three-codon sequence", (function () {
                return Jest.Expect[/* toEqual */12](/* :: */[
                            "Tryptophan",
                            /* [] */0
                          ], Jest.Expect[/* expect */0](ProteinTranslation$ProteinTranslation.proteins("UGGUAGUGG")));
              }));
        return Jest.test("Translation stops if STOP codon in middle of six-codon sequence", (function () {
                      return Jest.Expect[/* toEqual */12](/* :: */[
                                  "Tryptophan",
                                  /* :: */[
                                    "Cysteine",
                                    /* :: */[
                                      "Tyrosine",
                                      /* [] */0
                                    ]
                                  ]
                                ], Jest.Expect[/* expect */0](ProteinTranslation$ProteinTranslation.proteins("UGGUGUUAUUAAUGGUUU")));
                    }));
      }));

/*  Not a pure module */
