// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Isogram$Isogram = require("../src/Isogram.bs.js");

describe("Isograms", (function () {
        Jest.test("Empty string", (function () {
                return Jest.Expect[/* toBe */2](true, Jest.Expect[/* expect */0](Isogram$Isogram.is_isogram("")));
              }));
        Jest.test("Isogram with only lower case characters", (function () {
                return Jest.Expect[/* toBe */2](true, Jest.Expect[/* expect */0](Isogram$Isogram.is_isogram("isogram")));
              }));
        Jest.test("Word with one duplicated character", (function () {
                return Jest.Expect[/* toBe */2](false, Jest.Expect[/* expect */0](Isogram$Isogram.is_isogram("eleven")));
              }));
        Jest.test("Longest reported english isogram", (function () {
                return Jest.Expect[/* toBe */2](true, Jest.Expect[/* expect */0](Isogram$Isogram.is_isogram("subdermatoglyphic")));
              }));
        Jest.test("Word with duplicated character in mixed case", (function () {
                return Jest.Expect[/* toBe */2](false, Jest.Expect[/* expect */0](Isogram$Isogram.is_isogram("Alphabet")));
              }));
        Jest.test("Hypothetical isogrammic word with hyphen", (function () {
                return Jest.Expect[/* toBe */2](true, Jest.Expect[/* expect */0](Isogram$Isogram.is_isogram("thumbscrew-japingly")));
              }));
        Jest.test("Isogram with duplicated hyphen", (function () {
                return Jest.Expect[/* toBe */2](true, Jest.Expect[/* expect */0](Isogram$Isogram.is_isogram("six-year-old")));
              }));
        Jest.test("Made-up name that is an isogram", (function () {
                return Jest.Expect[/* toBe */2](true, Jest.Expect[/* expect */0](Isogram$Isogram.is_isogram("Emily Jung Schwartzkopf")));
              }));
        return Jest.test("Duplicated character in the middle", (function () {
                      return Jest.Expect[/* toBe */2](false, Jest.Expect[/* expect */0](Isogram$Isogram.is_isogram("accentor")));
                    }));
      }));

/*  Not a pure module */
