// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';


var AllYourBase_test = 0;

var AllYourBase = 0;

exports.AllYourBase_test = AllYourBase_test;
exports.AllYourBase = AllYourBase;
/* No side effect */
