// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");

var accumulate = List.map;

exports.accumulate = accumulate;
/* No side effect */
