// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';


var Acronym_test = 0;

var Acronym = 0;

exports.Acronym_test = Acronym_test;
exports.Acronym = Acronym;
/* No side effect */
