// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var $$String = require("bs-platform/lib/js/string.js");

function is_isogram(xs) {
  var partial_arg = (/\s+|-/g);
  var replaceWhitespaceOrHyphen = function (param) {
    return param.replace(partial_arg, "");
  };
  var ys = $$Array.of_list(List.sort_uniq($$String.compare, $$Array.to_list(Curry._1(replaceWhitespaceOrHyphen, xs.toLowerCase()).split("")))).join("");
  return ys.length === Curry._1(replaceWhitespaceOrHyphen, xs).length;
}

exports.is_isogram = is_isogram;
/* No side effect */
