// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';


var Allergies_test = 0;

var Allergies = 0;

exports.Allergies_test = Allergies_test;
exports.Allergies = Allergies;
/* No side effect */
