// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var $$String = require("bs-platform/lib/js/string.js");

function anagrams(w, ws) {
  var sort = function (w) {
    return $$Array.of_list(List.sort($$String.compare, $$Array.to_list(w.toLowerCase().split("")))).join("");
  };
  var y = sort(w);
  return List.filter((function (x) {
                  if (sort(x) === y) {
                    var w1 = x;
                    var w2 = w;
                    return w1.toLowerCase() !== w2.toLowerCase();
                  } else {
                    return false;
                  }
                }))(ws);
}

exports.anagrams = anagrams;
/* No side effect */
