// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Pangram$Pangram = require("../src/Pangram.bs.js");

describe("Pangram", (function () {
        Jest.test("sentence empty", (function () {
                return Jest.Expect[/* toEqual */12](false, Jest.Expect[/* expect */0](Pangram$Pangram.isPangram("")));
              }));
        Jest.test("recognizes a perfect lower case pangram", (function () {
                return Jest.Expect[/* toEqual */12](true, Jest.Expect[/* expect */0](Pangram$Pangram.isPangram("abcdefghijklmnopqrstuvwxyz")));
              }));
        Jest.test("pangram with only lower case", (function () {
                return Jest.Expect[/* toEqual */12](true, Jest.Expect[/* expect */0](Pangram$Pangram.isPangram("the quick brown fox jumps over the lazy dog")));
              }));
        Jest.test("missing character 'x'", (function () {
                return Jest.Expect[/* toEqual */12](false, Jest.Expect[/* expect */0](Pangram$Pangram.isPangram("a quick movement of the enemy will jeopardize five gunboats")));
              }));
        Jest.test("another missing character, e.g. 'h'", (function () {
                return Jest.Expect[/* toEqual */12](false, Jest.Expect[/* expect */0](Pangram$Pangram.isPangram("five boxing wizards jump quickly at it")));
              }));
        Jest.test("pangram with underscores", (function () {
                return Jest.Expect[/* toEqual */12](true, Jest.Expect[/* expect */0](Pangram$Pangram.isPangram("the_quick_brown_fox_jumps_over_the_lazy_dog")));
              }));
        Jest.test("pangram with numbers", (function () {
                return Jest.Expect[/* toEqual */12](true, Jest.Expect[/* expect */0](Pangram$Pangram.isPangram("the 1 quick brown fox jumps over the 2 lazy dogs")));
              }));
        Jest.test("missing letters replaced by numbers", (function () {
                return Jest.Expect[/* toEqual */12](false, Jest.Expect[/* expect */0](Pangram$Pangram.isPangram("7h3 qu1ck brown fox jumps ov3r 7h3 lazy dog")));
              }));
        Jest.test("pangram with mixed case and punctuation", (function () {
                return Jest.Expect[/* toEqual */12](true, Jest.Expect[/* expect */0](Pangram$Pangram.isPangram("\"Five quacking Zephyrs jolt my wax bed.\"")));
              }));
        return Jest.test("upper and lower case versions of the same character should not be counted separately", (function () {
                      return Jest.Expect[/* toEqual */12](false, Jest.Expect[/* expect */0](Pangram$Pangram.isPangram("the quick brown fox jumps over with lazy FX")));
                    }));
      }));

/*  Not a pure module */
