// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");

var allergies = /* array */[
  "eggs",
  "peanuts",
  "shellfish",
  "strawberries",
  "tomatoes",
  "chocolate",
  "pollen",
  "cats"
];

function scoreToAllergies(s) {
  if (s !== 0) {
    return List.append(/* :: */[
                s % 2,
                /* [] */0
              ], scoreToAllergies(s / 2 | 0));
  } else {
    return /* [] */0;
  }
}

function toList(s) {
  return List.filter((function (x) {
                  return x !== "";
                }))(List.mapi((function (i, x) {
                    var match = x === 1;
                    if (match) {
                      return Caml_array.caml_array_get(allergies, i);
                    } else {
                      return "";
                    }
                  }), scoreToAllergies(s % 256)));
}

function isAllergicTo(x, score) {
  return List.exists((function (y) {
                return y === x;
              }), toList(score));
}

exports.isAllergicTo = isAllergicTo;
exports.toList = toList;
/* No side effect */
