// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Change$Change = require("../src/Change.bs.js");

describe("Change", (function () {
        Jest.test("single coin change", (function () {
                return Jest.Expect[/* toEqual */12](/* Some */[/* :: */[
                              25,
                              /* [] */0
                            ]], Jest.Expect[/* expect */0](Change$Change.makeChange(25, /* :: */[
                                    1,
                                    /* :: */[
                                      5,
                                      /* :: */[
                                        10,
                                        /* :: */[
                                          25,
                                          /* :: */[
                                            100,
                                            /* [] */0
                                          ]
                                        ]
                                      ]
                                    ]
                                  ])));
              }));
        Jest.test("multiple coin change", (function () {
                return Jest.Expect[/* toEqual */12](/* Some */[/* :: */[
                              5,
                              /* :: */[
                                10,
                                /* [] */0
                              ]
                            ]], Jest.Expect[/* expect */0](Change$Change.makeChange(15, /* :: */[
                                    1,
                                    /* :: */[
                                      5,
                                      /* :: */[
                                        10,
                                        /* :: */[
                                          25,
                                          /* :: */[
                                            100,
                                            /* [] */0
                                          ]
                                        ]
                                      ]
                                    ]
                                  ])));
              }));
        Jest.test("change with Lilliputian Coins", (function () {
                return Jest.Expect[/* toEqual */12](/* Some */[/* :: */[
                              4,
                              /* :: */[
                                4,
                                /* :: */[
                                  15,
                                  /* [] */0
                                ]
                              ]
                            ]], Jest.Expect[/* expect */0](Change$Change.makeChange(23, /* :: */[
                                    1,
                                    /* :: */[
                                      4,
                                      /* :: */[
                                        15,
                                        /* :: */[
                                          20,
                                          /* :: */[
                                            50,
                                            /* [] */0
                                          ]
                                        ]
                                      ]
                                    ]
                                  ])));
              }));
        Jest.test("change with Lower Elbonia Coins", (function () {
                return Jest.Expect[/* toEqual */12](/* Some */[/* :: */[
                              21,
                              /* :: */[
                                21,
                                /* :: */[
                                  21,
                                  /* [] */0
                                ]
                              ]
                            ]], Jest.Expect[/* expect */0](Change$Change.makeChange(63, /* :: */[
                                    1,
                                    /* :: */[
                                      5,
                                      /* :: */[
                                        10,
                                        /* :: */[
                                          21,
                                          /* :: */[
                                            25,
                                            /* [] */0
                                          ]
                                        ]
                                      ]
                                    ]
                                  ])));
              }));
        Jest.test("large target values", (function () {
                return Jest.Expect[/* toEqual */12](/* Some */[/* :: */[
                              2,
                              /* :: */[
                                2,
                                /* :: */[
                                  5,
                                  /* :: */[
                                    20,
                                    /* :: */[
                                      20,
                                      /* :: */[
                                        50,
                                        /* :: */[
                                          100,
                                          /* :: */[
                                            100,
                                            /* :: */[
                                              100,
                                              /* :: */[
                                                100,
                                                /* :: */[
                                                  100,
                                                  /* :: */[
                                                    100,
                                                    /* :: */[
                                                      100,
                                                      /* :: */[
                                                        100,
                                                        /* :: */[
                                                          100,
                                                          /* [] */0
                                                        ]
                                                      ]
                                                    ]
                                                  ]
                                                ]
                                              ]
                                            ]
                                          ]
                                        ]
                                      ]
                                    ]
                                  ]
                                ]
                              ]
                            ]], Jest.Expect[/* expect */0](Change$Change.makeChange(999, /* :: */[
                                    1,
                                    /* :: */[
                                      2,
                                      /* :: */[
                                        5,
                                        /* :: */[
                                          10,
                                          /* :: */[
                                            20,
                                            /* :: */[
                                              50,
                                              /* :: */[
                                                100,
                                                /* [] */0
                                              ]
                                            ]
                                          ]
                                        ]
                                      ]
                                    ]
                                  ])));
              }));
        Jest.test("possible change without unit coins available", (function () {
                return Jest.Expect[/* toEqual */12](/* Some */[/* :: */[
                              2,
                              /* :: */[
                                2,
                                /* :: */[
                                  2,
                                  /* :: */[
                                    5,
                                    /* :: */[
                                      10,
                                      /* [] */0
                                    ]
                                  ]
                                ]
                              ]
                            ]], Jest.Expect[/* expect */0](Change$Change.makeChange(21, /* :: */[
                                    2,
                                    /* :: */[
                                      5,
                                      /* :: */[
                                        10,
                                        /* :: */[
                                          20,
                                          /* :: */[
                                            50,
                                            /* [] */0
                                          ]
                                        ]
                                      ]
                                    ]
                                  ])));
              }));
        Jest.test("another possible change without unit coins available", (function () {
                return Jest.Expect[/* toEqual */12](/* Some */[/* :: */[
                              4,
                              /* :: */[
                                4,
                                /* :: */[
                                  4,
                                  /* :: */[
                                    5,
                                    /* :: */[
                                      5,
                                      /* :: */[
                                        5,
                                        /* [] */0
                                      ]
                                    ]
                                  ]
                                ]
                              ]
                            ]], Jest.Expect[/* expect */0](Change$Change.makeChange(27, /* :: */[
                                    4,
                                    /* :: */[
                                      5,
                                      /* [] */0
                                    ]
                                  ])));
              }));
        Jest.test("no coins make 0 change", (function () {
                return Jest.Expect[/* toEqual */12](/* Some */[/* [] */0], Jest.Expect[/* expect */0](Change$Change.makeChange(0, /* :: */[
                                    1,
                                    /* :: */[
                                      5,
                                      /* :: */[
                                        10,
                                        /* :: */[
                                          21,
                                          /* :: */[
                                            25,
                                            /* [] */0
                                          ]
                                        ]
                                      ]
                                    ]
                                  ])));
              }));
        Jest.test("error testing for change smaller than the smallest of coins", (function () {
                return Jest.Expect[/* toEqual */12](/* None */0, Jest.Expect[/* expect */0](Change$Change.makeChange(3, /* :: */[
                                    5,
                                    /* :: */[
                                      10,
                                      /* [] */0
                                    ]
                                  ])));
              }));
        Jest.test("error if no combination can add up to target", (function () {
                return Jest.Expect[/* toEqual */12](/* None */0, Jest.Expect[/* expect */0](Change$Change.makeChange(94, /* :: */[
                                    5,
                                    /* :: */[
                                      10,
                                      /* [] */0
                                    ]
                                  ])));
              }));
        return Jest.test("cannot find negative change values", (function () {
                      return Jest.Expect[/* toEqual */12](/* None */0, Jest.Expect[/* expect */0](Change$Change.makeChange(-5, /* :: */[
                                          1,
                                          /* :: */[
                                            2,
                                            /* :: */[
                                              5,
                                              /* [] */0
                                            ]
                                          ]
                                        ])));
                    }));
      }));

/*  Not a pure module */
