// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';


var Isogram_test = 0;

var Isogram = 0;

exports.Isogram_test = Isogram_test;
exports.Isogram = Isogram;
/* No side effect */
